---
title: "Simple document"
output: github_document
---

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## Import some data

I want to import 'FAS_litters.csv'.

```{r}
litters_df = read_csv("data/FAS_litters.csv")
```

Yay! I imported the dataset. Now I want better names.

```{r}
names(litters_df)

litters_df = janitor::clean_names(litters_df)
```

Yay! Now I have better names. Let's look at the dataset.

```{r}
litters_df

head(litters_df)
tail(litters_df)
```

One I use a lot is:

```{r, eval=FALSE}
view(litters_df)
```

Here's 'skimr':

```{r}
skimr::skim(litters_df)
```


## Arument in 'read_csv'
```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    skip = 5,
    col_names = FALSE,
    na = "Low8")
```


## Parsing columns

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols('GD of Birth' = col_integer())
)

```


## Reading ftom Excel

Reading MLB data

```{r}
mlb11_df = read_excel("data/mlb11.xlsx")
```

LotR Words is next.

```{r}
fellow_df = read_excel("data/LotR_Words.xlsx", range = "B3:D6")
```


## Read a SAS file

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```


